pool:
  name: jldeenlinux

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Jfrog Artifactory'
    dockerFile: Dockerfile

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Jfrog Artifactory'
    command: 'Push an image'

- task: HelmInstaller@0
  displayName: 'Install Helm 2.9.1'

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    command: package
    chartPath: charts/spring-boot-websocket-chat-demo

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **/*.jar
     **/*.zip
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
